convert by-nc-nd.eu.png  -colorspace CMYK EPDF:by-nc-nd.eu.pdf
convert by-nc-nd.png     -colorspace CMYK EPDF:by-nc-nd.pdf
convert by-nc-nd.s.png   -colorspace CMYK EPDF:by-nc-nd-s.pdf
convert by-nc-sa.eu.png  -colorspace CMYK EPDF:by-nc-sa.eu.pdf
convert by-nc-sa.png     -colorspace CMYK EPDF:by-nc-sa.pdf
convert by-nc-sa.s.png   -colorspace CMYK EPDF:by-nc-sa-s.pdf
convert by-nc.eu.png     -colorspace CMYK EPDF:by-nc.eu.pdf
convert by-nc.png        -colorspace CMYK EPDF:by-nc.pdf
convert by-nc.s.png      -colorspace CMYK EPDF:by-nc-s.pdf
convert by-nd.png        -colorspace CMYK EPDF:by-nd.pdf
convert by-nd.s.png      -colorspace CMYK EPDF:by-nd-s.pdf
convert by-sa.png        -colorspace CMYK EPDF:by-sa.pdf
convert by-sa.s.png      -colorspace CMYK EPDF:by-sa-s.pdf
convert by.png           -colorspace CMYK EPDF:by.pdf
convert by.s.png         -colorspace CMYK EPDF:by-s.pdf
convert cc-zero.png      -colorspace CMYK EPDF:cc-zero.pdf
convert cc-zero.s.png    -colorspace CMYK EPDF:cc-zero-s.pdf
convert pdf-property.png -colorspace CMYK EPDF:pdf-property.pdf
